import assert from "node:assert/strict";
import fs from "node:fs";

const html = fs.readFileSync(new URL("../sidepanel.html", import.meta.url), "utf8");
const script = fs.readFileSync(new URL("../sidepanel.js", import.meta.url), "utf8");
const styles = fs.readFileSync(new URL("../styles.css", import.meta.url), "utf8");
const manifest = JSON.parse(fs.readFileSync(new URL("../manifest.json", import.meta.url), "utf8"));
const packageJson = JSON.parse(fs.readFileSync(new URL("../package.json", import.meta.url), "utf8"));
const ids = new Set([...html.matchAll(/\bid="([^"]+)"/g)].map((match) => match[1]));
const references = new Set([...script.matchAll(/elements\.([A-Za-z][A-Za-z0-9]*)/g)].map((match) => match[1]));

const missing = [...references].filter((id) => !ids.has(id));
assert.deepEqual(missing, [], `sidepanel.js references missing HTML ids: ${missing.join(", ")}`);
assert.equal(ids.size, [...html.matchAll(/\bid="([^"]+)"/g)].length, "HTML ids must be unique");
assert.match(html, /id="settingsButton"[^>]*aria-controls="settingsPanel"[^>]*aria-expanded="false"/);
assert.match(html, /class="settings-card settings-drawer hidden" id="settingsPanel"/);
assert.match(html, /id="thinkingEnabled"[^>]*checked/);
assert.match(html, /id="compatibleStreaming"[^>]*type="checkbox"/);
assert.match(html, /兼容接口启用流式输出（实验性）/);
assert.match(html, /<option value="high">High（默认）<\/option>/);
assert.match(html, /<option value="max">Max（复杂任务）<\/option>/);
assert.match(html, /id="planMode"/);
assert.match(html, /id="directModeButton"[^>]*aria-pressed="true"/);
assert.match(html, /id="planModeButton"[^>]*aria-pressed="false"/);
assert.match(html, /class="chat-card"/);
assert.match(html, /id="conversation"[^>]*role="log"/);
assert.match(html, /id="clearChatButton"/);
assert.match(html, /id="conversationEmpty"/);
assert.match(html, /id="scrollToLatestButton"/);
assert.match(html, /id="queuePanel"/);
assert.match(html, /id="queueList"/);
assert.match(html, /id="resumeQueueButton"/);
assert.match(html, /id="consoleContextChip"/);
assert.match(html, /id="includeConsole"[^>]*aria-label="包含 Earth Engine Console 上下文"/);
assert.match(html, /id="includeConsoleLabel"[^>]*aria-live="polite"/);
assert.match(html, /id="sendButton"[^>]*disabled/);
assert.match(html, /id="copyButton"/);
assert.match(html, /id="candidateHint"/);
assert.match(html, /id="candidateStatusBadge"/);
assert.match(html, /id="candidateCodeView"/);
assert.match(html, /关闭代码卡/);
assert.match(html, /id="confirmPlanButton"/);
assert.match(html, /id="continuePlanButton"/);
assert.match(html, /id="cancelPlanButton"/);
assert.match(html, /id="planRevisionBadge"/);
assert.ok(html.indexOf('id="conversation"') < html.indexOf('id="planPanel"'), "plan panel must live inside the chat log");
assert.ok(html.indexOf('id="conversation"') < html.indexOf('id="toolResults"'), "tool results must live inside the chat log");
assert.match(script, /const ACTIVE_PLAN_KEY = "activePlanV1"/);
assert.match(script, /const CHAT_HISTORY_KEY = "chatHistoryV1"/);
assert.match(script, /const CODE_CANDIDATE_KEY = "codeCandidateV1"/);
assert.match(script, /const MESSAGE_QUEUE_KEY = "messageQueueV1"/);
assert.match(script, /let initialized = false/);
assert.match(script, /async function generateFromConfirmedPlan\(\) \{\s+if \(!initialized\)/);
assert.match(script, /initialized = true;\s+if \(!busy\) \{\s+setBusy\(false\)/);
assert.match(script, /initialize\(\)\.catch\(handleInitializeFailure\)/);
assert.match(script, /function handleInitializeFailure\(error\)/);
assert.match(script, /function renderInitializeRetry\(error\)/);
assert.match(script, /async function retryInitialize\(\)/);
assert.match(script, /重试初始化/);
assert.match(script, /if \(eventsBound\) return/);
assert.match(styles, /\.init-retry-notice\s*\{/);
assert.match(script, /chrome\.runtime\.connect\(\{ name: "AI_CHAT_STREAM" \}\)/);
assert.match(script, /兼容模式不支持实时思考/);
assert.match(script, /isOfficialDeepSeekV4Flash\(settings\?\.baseUrl, settings\?\.model\)/);
assert.match(script, /第一步必须创建 TODO List/);
assert.match(script, /禁止直接给结论或代码/);
assert.match(script, /function renderPlanTodoList\(plan\)/);
assert.match(script, /plan\.todoList\?\.length/);
assert.match(script, /upsertPlanAnswerText\(elements\.prompt\.value/);
assert.match(script, /已叠加 \$\{answerCount\} 个问题的答案/);
assert.match(script, /if \(!currentSettings\.hasApiKey\) openSettings\(\{ focusKey: true \}\)/);
assert.match(script, /baseRevision: baseState\?\.revision/);
assert.match(script, /tabId: baseState\?\.tabId/);
assert.match(script, /session\.userTurns\.at\(-1\)/);
assert.doesNotMatch(script, /\[session\.originalRequest, \.\.\.session\.userTurns\]/);
assert.match(script, /formatPlanTranscript\(activePlan\)/);
assert.match(script, /recordSourceSnapshot\(toolResult\)/);
assert.match(script, /const newSession = !activePlan\?\.originalRequest/);
assert.match(script, /const firstResearchRound = !activePlan\?\.plan/);
assert.match(script, /entry\.role === "assistant" && \["source", "plan"\]\.includes\(entry\.purpose\)/);
assert.match(script, /本轮仍会基于你的需求和官方资料制定计划/);
assert.doesNotMatch(script, /throw new Error\("无法连接 Earth Engine 编辑器，请取消代码上下文选项或打开 Code Editor"\)/);
assert.doesNotMatch(script, /无法读取当前 GEE 编辑器上下文/);
assert.match(script, /navigator\.clipboard\.writeText\(candidate\.code\)/);
assert.match(script, /markCodeCandidateApplied\(candidate, mode\)/);
assert.match(script, /function renderCandidateCard\(\{ scroll = false \} = \{\}\)/);
assert.match(script, /elements\.candidatePanel\.scrollIntoView/);
assert.match(script, /if \(scroll && follow\)/);
assert.match(script, /function drainMessageQueue\(\)/);
assert.match(script, /enqueuePrompt\(prompt, planRequest\)/);
assert.match(script, /queuePaused = true/);
assert.match(script, /function handleConversationScroll\(\)/);
assert.match(script, /function renderConsoleReadStatus\(consoleRead = editorState\?\.consoleRead\)/);
assert.match(script, /createConsoleContextSection\(state, elements\.includeConsole\.checked\)/);
assert.match(script, /state\?\.consoleRead\?\.status === "captured" && state\.consoleText/);
assert.match(script, /禁止推测、虚构或把代码分析当作真实 Console 错误/);
assert.match(script, /setScrollToLatestVisibility/);
assert.match(script, /function describePlanTurnError\(error, stage\)/);
assert.match(script, /模型最终计划未通过结构校验/);
assert.match(script, /setRequestErrorStatus\(error, \{/);
assert.match(styles, /\.status-error\s*\{[\s\S]*?white-space:\s*normal/);
assert.match(styles, /html,[\s\S]*?body\s*\{[\s\S]*?overflow:\s*hidden/);
assert.match(styles, /\.conversation\s*\{[\s\S]*?overflow-y:\s*auto/);
assert.match(styles, /\.context-chip\.console-status-captured:has\(input:checked\)/);
assert.match(styles, /\.context-chip\.console-status-empty:has\(input:checked\)/);
assert.match(styles, /\.context-chip\.console-status-unavailable:has\(input:checked\)/);
assert.match(script, /elements\.conversation\.appendChild\(elements\.candidatePanel\)/);
const applyCandidateStart = script.indexOf("async function applyCandidate");
const copyCandidateStart = script.indexOf("async function copyCandidate");
assert.doesNotMatch(script.slice(applyCandidateStart, copyCandidateStart), /dismissCandidate\(\)/);
const sendPromptStart = script.indexOf("async function sendPrompt");
const directTurnStart = script.indexOf("async function runDirectTurn");
const sendPromptBody = script.slice(sendPromptStart, directTurnStart);
assert.ok(sendPromptBody.indexOf("setBusy(true)") < sendPromptBody.indexOf("await runPlanTurn"), "send must lock before awaiting a request");
assert.ok(sendPromptBody.indexOf('elements.prompt.value = ""') < sendPromptBody.indexOf("await runPlanTurn"), "sent text must leave the input before awaiting a response");
assert.equal(manifest.version, "0.4.0");
assert.ok(manifest.permissions.includes("clipboardWrite"));
assert.ok(manifest.permissions.includes("unlimitedStorage"));
assert.match(script, /import \{ setWithQuotaEviction \} from "\.\/lib\/storage\.js"/);
assert.match(script, /function reportPersistFailure\(kind, error\)/);
assert.match(script, /本地保存失败，仅保留在当前会话/);
assert.match(script, /PERSIST_FAILURE_NOTIFY_COOLDOWN_MS = 10000/);
assert.match(script, /appendMessage\("user", prompt, \{ purpose: "direct" \}\)/);
assert.match(script, /\.filter\(\(entry\) => entry\.purpose === "direct" && \["user", "assistant"\]\.includes\(entry\.role\)\)/);
assert.match(script, /directConversation = alignConversationToUser\(/);
assert.match(script, /elements\.compatibleStreaming\.checked = currentSettings\.compatibleStreaming === true/);
assert.match(script, /compatibleStreaming: elements\.compatibleStreaming\.checked/);
assert.equal(packageJson.version, manifest.version);

console.log("UI consistency tests passed.");
